-- CreateTable
CREATE TABLE `SKU` (
    `ID` VARCHAR(191) NOT NULL,
    `SKU` VARCHAR(50) NOT NULL,
    `DESCRIPTION` VARCHAR(200) NULL,
    `COMERCIAL_DESCRIPTION` VARCHAR(200) NULL,
    `STATUS` ENUM('PRE_REGISTER', 'COMPLETED_REGISTER', 'ACTIVE', 'INACTIVE', 'CANCEL') NOT NULL DEFAULT 'PRE_REGISTER',
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `SKU_SKU_key`(`SKU`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
